# Generated by Django 4.1.2 on 2022-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Recommended resolution: 1040px * 585px",
                null=True,
                upload_to="blog-posts/",
                verbose_name="Image",
            ),
        ),
    ]
